[pytest]
testpaths = tests
python_files = test_*.py
addopts = -q
filterwarnings =
    ignore:websockets\.legacy is deprecated.*:DeprecationWarning
    ignore:'asyncio\.iscoroutinefunction' is deprecated.*:DeprecationWarning
    ignore:Instantiating a struct using a dictionary is deprecated.*
