from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "src" / "risk" / "CarmineRiskTables.vy"


def main() -> None:
    lines: list[str] = []
    lines.append("# pragma version ^0.4.3")
    lines.append("")
    lines.append("BPS: constant(uint256) = 10_000")
    lines.append("RAY: constant(uint256) = 10**27")
    lines.append("TABLE_SIZE: constant(uint256) = 1280")
    lines.append("")
    for idx in range(1280):
        name = f"RISK_WEIGHT_{idx:04d}"
        weight = 1_000 + ((idx * 37) % 8_000)
        lines.append(f"{name}: constant(uint256) = {weight}")
    lines.append("")
    lines.append("@external")
    lines.append("@view")
    lines.append("def table_size() -> uint256:")
    lines.append("    return TABLE_SIZE")
    lines.append("")
    lines.append("@internal")
    lines.append("@view")
    lines.append("def _coarse_discount_bps(_bucket: uint256) -> uint256:")
    lines.append("    if _bucket == 0:")
    lines.append("        return 0")
    lines.append("    if _bucket <= 4:")
    lines.append("        return 150")
    lines.append("    if _bucket <= 8:")
    lines.append("        return 300")
    lines.append("    if _bucket <= 16:")
    lines.append("        return 500")
    lines.append("    if _bucket <= 32:")
    lines.append("        return 800")
    lines.append("    if _bucket <= 64:")
    lines.append("        return 1_200")
    lines.append("    return 1_800")
    lines.append("")
    lines.append("@internal")
    lines.append("@view")
    lines.append("def _bucket_from_health(_health_ray: uint256) -> uint256:")
    lines.append("    if _health_ray < RAY:")
    lines.append("        return 64")
    lines.append("    if _health_ray < RAY * 105 // 100:")
    lines.append("        return 32")
    lines.append("    if _health_ray < RAY * 115 // 100:")
    lines.append("        return 16")
    lines.append("    if _health_ray < RAY * 135 // 100:")
    lines.append("        return 8")
    lines.append("    if _health_ray < RAY * 175 // 100:")
    lines.append("        return 4")
    lines.append("    return 1")
    lines.append("")
    lines.append("@external")
    lines.append("@view")
    lines.append("def coarse_discount_bps(_bucket: uint256) -> uint256:")
    lines.append("    return self._coarse_discount_bps(_bucket)")
    lines.append("")
    lines.append("@external")
    lines.append("@view")
    lines.append("def bucket_from_health(_health_ray: uint256) -> uint256:")
    lines.append("    return self._bucket_from_health(_health_ray)")
    lines.append("")
    lines.append("@external")
    lines.append("@view")
    lines.append("def weighted_discount_bps(_health_ray: uint256, _volatility_bps: uint256) -> uint256:")
    lines.append("    bucket: uint256 = self._bucket_from_health(_health_ray)")
    lines.append("    base: uint256 = self._coarse_discount_bps(bucket)")
    lines.append("    add_on: uint256 = _volatility_bps // 20")
    lines.append("    if base + add_on > 5_000:")
    lines.append("        return 5_000")
    lines.append("    return base + add_on")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
